AIP/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path , include
from . import views
from django.views.generic.base import TemplateView # new

app_name = 'AIP'

urlpatterns = [
    path('', views.index, name='index'),
    path('pickskill/', views.pickskill, name='pickskill'),
    path('begin/', views.begin, name='begin'),
    path('quiz/', views.quiz, name='quiz'),
    path('quizsimple/', views.quizsimple, name='quizsimple'),
    path('upload/', views.upload, name='upload'),
    path('comment/', views.comment, name='comment'),
    path('question/', views.question, name='question'),
    path('logout/', views.logout, name='logout'),
    path('export/', views.export, name='export'),
    path('add/', views.add, name='add'),
    path('questionupload/', views.questionupload, name='questionupload'),
    path('scores/', views.scores, name='scores'),
    path('quizzes/', views.quizzes,name='quizzes'),
    path('addquiz/', views.addquiz,name='addquiz'),
    path('addquestion/', views.addquestion, name='addquestion'),
    path('addquestion1/', views.addquestion1, name='addquestion1'),
    path('quizlist/', views.quizbucket, name='quizbucket'),
    path('quiz/<int:pk>/', views.takequiz, name='takequiz'),
    path('searchquiz/', views.searchquiz, name='searchquiz'),
    path('compare/', views.compare, name='compare'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Portal/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("AIP.urls")),
    path('accounts/', include('allauth.urls')),

]

AIP/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Quiz(models.Model):
    quiz_name                        = models.CharField(max_length=100,default='')
    quiz_OrgIdentifier               = models.CharField(max_length=40,default='')
    quiz_questions                   = models.TextField(null=True)
    quiz_noofquest                   = models.IntegerField(default=0)

    def __str__(self):
        return self.quiz_name + "_" + self.quiz_OrgIdentifier

class Question(models.Model):
    q_subject                    = models.CharField(max_length=40)
    q_cat                        = models.CharField(max_length=40)
    q_rank                       = models.CharField(max_length=20)
    q_text                       = models.TextField(null=True,default='')
    q_option1                    = models.CharField(max_length=200,default='')
    q_option2                    = models.CharField(max_length=200,default='')
    q_option3                    = models.CharField(max_length=200,default='')
    q_option4                    = models.CharField(max_length=200,default='')
    q_answer                     = models.CharField(max_length=20)
    q_ask_time                   = models.DateTimeField(default=datetime.now, blank=True)
    no_times_ques_served         = models.IntegerField(default=0)
    no_times_anwered_correctly   = models.IntegerField(default=0)
    no_times_anwered_incorrectly = models.IntegerField(default=0)
    difficulty_score             = models.DecimalField(default=0,max_digits = 5, decimal_places = 2)

    def __str__(self):
        return self.q_text

class Answer(models.Model):
    question                     = models.ForeignKey(Question, on_delete=models.CASCADE)
    ans_option                   = models.CharField(max_length=20)
    is_correct                   = models.BooleanField(default=False)
    ans_time                     = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.ans_option

class Result(models.Model):
    c_user                      = models.CharField(max_length=100)
    c_quiz_name                 = models.CharField(max_length=100,default='')
    c_tot_score                 = models.IntegerField(default=0)
    c_cat_scores                = models.TextField(null=True,default=0)
    c_comment                   = models.TextField(null=True,default='')
    c_new_quest                 = models.TextField(null=True,default='')
    c_attempt_date              = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.c_user

AIP/forms.py
from django.db import models

from django import forms
from .models import Question

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        labels = {
            'q_subject'                     : 'Subject',
            'q_cat'                         : 'Category',
            'q_rank'                        : 'Rank',
            'q_text'                        : 'Question',
            'q_option1'                     : 'Answer Option1',
            'q_option2'                     : 'Answer Option2',
            'q_option3'                     : 'Answer Option3',
            'q_option4'                     : 'Answer Option4',
            'q_answer'                      : 'Answer',
        }

        fields = ('q_subject','q_cat','q_rank','q_text','q_option1','q_option2','q_option3','q_option4','q_answer')
        #fields = '__all__'

AIP/views.py
import datetime
from django.http import HttpResponse, request, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.utils.datastructures import MultiValueDictKeyError
from django.core.files.storage import FileSystemStorage
from django.views import generic

from .models import Question, Answer, Result,Quiz
from django.http import HttpResponse
import json
import random
import csv, io
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from .forms import QuestionForm
from django.contrib.auth.models import User
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,UpdateView)

def index(request):
    return render(request, 'AIP/index.html')


def pickskill(request):
    request.session['user'] = request.user.get_full_name()
    user = request.session['user']
    Result.objects.create(c_user=user)
    context = {'user':user}
    return render(request, 'AIP/pickskill.html',context)

def begin(request):
    if request.method == 'POST':
        subject = request.POST['skill']
        rank = request.POST['proficiency']
        context = {'subject': subject, 'rank': rank}
        request.session['skill'] = subject
        request.session['proficiency'] = rank
        request.session['curr_difficulty_score'] = 1
        request.session['total_q_asked'] = 1
        request.session['total_q_ans_correct'] = 0
        request.session['counter'] = 0
        cat_dict = {'Introduction': 0, 'Syntax': 0, 'OOPS': 0, 'NativeDataTypes': 0, 'FileAndExceptionHandling': 0,
                    'Function': 0, 'Advanced': 0}
        request.session['cat_dict'] = cat_dict
        request.session['score'] = 0

        if rank == 'Adaptive':
            return render(request, 'AIP/begin.html', context)
        else:
            return render(request, 'AIP/beginsimple.html', context)


def quizsimple(request):
    subject = request.session['skill']
    rank = request.session['proficiency']
    total_q_asked = request.session['total_q_asked']
    total_q_ans_correct = request.session['total_q_ans_correct']
    counter = request.session['counter']
    score = request.session['score']
    cat_dict = request.session['cat_dict']
    user = request.session['user']

    questions = Question.objects.filter(q_subject=subject, q_rank=rank)
    max = Question.objects.filter(q_subject=subject, q_rank=rank).count()
    ind = random.randint(1, max)
    question = questions[ind]
    context = {'total_q_asked': total_q_asked, 'question': question}
    if request.method == 'POST':
        option = request.POST.get('options')
        q = Question(question.pk)
        ans = Answer()
        ans.question = q
        question.no_times_ques_served += 1

        total_q_asked += 1
        if question.q_answer == option:
            ans.ans_option = option
            ans.is_correct = True
            question.no_times_anwered_correctly += 1
            total_q_ans_correct += 1
            cat_dict[question.q_cat] += 1
            ans.save()
        else:
            ans.ans_option = option
            ans.is_correct = False
            question.no_times_anwered_incorrectly += 1
            ans.save()

        Question.objects.filter(pk=q.pk).update(no_times_ques_served=question.no_times_ques_served,
                                                no_times_anwered_correctly=question.no_times_anwered_correctly,
                                                no_times_anwered_incorrectly=question.no_times_anwered_incorrectly)
        if counter == 20 or request.POST.get('END') == 'STOP':
            score1 = (total_q_ans_correct / (total_q_asked - 1)) * 100
            score = round(score1)
            cat_scores = json.dumps(cat_dict)
            Result.objects.filter(c_user=user).update(c_tot_score=score)
            Result.objects.filter(c_user=user).update(c_cat_scores=cat_scores)
            score_context = {'score': score, 'cat_dict': cat_dict, 'total_q_asked': total_q_asked - 1,
                             'total_q_ans_correct': total_q_ans_correct}
            return render(request, 'AIP/report.html', score_context)

        counter += 1
        request.session['score'] = score
        request.session['counter'] = counter
        request.session['total_q_asked'] = total_q_asked
        request.session['total_q_ans_correct'] = total_q_ans_correct
        request.session['cat_dict'] = cat_dict

        questions = Question.objects.filter(q_subject=subject, q_rank=rank)
        max = Question.objects.filter(q_subject=subject, q_rank=rank).count()
        ind = random.randint(1, max)
        question = questions[ind]
        context = {'total_q_asked': total_q_asked, 'question': question}
        return render(request, 'AIP/quizsimple.html', context)
    else:
        # this is GET flow of 1st question
        return render(request, 'AIP/quizsimple.html', context)


def quiz(request):
    subject = request.session['skill']
    rank = request.session['proficiency']
    curr_difficulty_score = request.session['curr_difficulty_score']
    total_q_asked = request.session['total_q_asked']
    total_q_ans_correct = request.session['total_q_ans_correct']
    score = request.session['score']
    cat_dict = request.session['cat_dict']
    user = request.session['user']
    counter = request.session['counter']

    questions = Question.objects.filter(q_subject=subject, q_rank=rank).filter(difficulty_score__gt=curr_difficulty_score).order_by('difficulty_score')
    question = questions[0]
    context = {'total_q_asked': total_q_asked, 'question': question}

    if request.method == 'POST':
        option = request.POST.get('options')
        q = Question(question.pk)
        ans = Answer()
        ans.question = q
        question.no_times_ques_served += 1
        total_q_asked += 1
        if question.q_answer == option:
            ans.ans_option = option
            ans.is_correct = True
            question.no_times_anwered_correctly += 1
            total_q_ans_correct += 1
            cat_dict[question.q_cat] += 1
            ans.save()
        else:
            ans.ans_option = option
            ans.is_correct = False
            question.no_times_anwered_incorrectly += 1
            ans.save()

        Question.objects.filter(pk=q.pk).update(no_times_ques_served=question.no_times_ques_served,
                                                no_times_anwered_correctly=question.no_times_anwered_correctly,
                                                no_times_anwered_incorrectly=question.no_times_anwered_incorrectly,
                                                difficulty_score=curr_difficulty_score)

        if counter == 20 or request.POST.get('END') == 'STOP':
            score1 = (total_q_ans_correct / (total_q_asked - 1)) * 100
            score = round(score1)
            cat_scores = json.dumps(cat_dict)
            Result.objects.filter(c_user=user).update(c_tot_score=score)
            Result.objects.filter(c_user=user).update(c_cat_scores=cat_scores)
            score_context = {'score': score, 'cat_dict': cat_dict, 'total_q_asked': total_q_asked - 1,
                             'total_q_ans_correct': total_q_ans_correct}
            return render(request, 'AIP/report.html', score_context)

        counter += 1
        request.session['counter'] = counter
        request.session['score'] = score
        request.session['total_q_asked'] = total_q_asked
        request.session['total_q_ans_correct'] = total_q_ans_correct
        request.session['curr_difficulty_score'] = curr_difficulty_score
        request.session['cat_dict'] = cat_dict

        # curr_difficulty_score = question.no_times_anwered_incorrectly / question.no_times_anwered_incorrectly + question.no_times_anwered_correctly
        curr_difficulty_score = question.no_times_anwered_incorrectly / question.no_times_ques_served
        questions = Question.objects.filter(q_subject=subject, q_rank=rank).filter(
            difficulty_score__gt=curr_difficulty_score).order_by('difficulty_score')
        question = questions[0]
        context = {'total_q_asked': total_q_asked, 'question': question}
        return render(request, 'AIP/quiz.html', context)
    else:
        return render(request, 'AIP/quiz.html', context)


def comment(request):
    context = {}
    user = request.session['user']
    if request.method == 'POST':
        comment = request.POST.get('comment')
        Result.objects.filter(c_user=user).update(c_comment=comment)
        context['commsuccess'] = "Comment added . Thank You !"
        return render(request, 'AIP/report.html', context)


def question(request):
    context = {}
    user = request.session['user']
    if request.method == 'POST':
        question = request.POST.get('question')
        Result.objects.filter(c_user=user).update(c_new_quest=question)
        context['quessuccess'] = "Question added . Thank You !"
        return render(request, 'AIP/report.html', context)


def upload(request):
    context = {}
    if request.method == 'POST':
        try:
            uploaded_file = request.FILES['document']
        except MultiValueDictKeyError:
            return HttpResponse("Please upload a file")

        fs = FileSystemStorage()
        name = fs.save(uploaded_file.name, uploaded_file)
        context['url'] = fs.url(name)
    return render(request, 'AIP/report.html', context)


def logout(request):
    try:
        del request.session['user']
    except KeyError:
        pass

    return render(request, 'AIP/index.html')


def export(request):
    response = HttpResponse(content_type='text/csv')
    writer = csv.writer(response)
    writer.writerow(
        ['q_subject', 'q_cat', 'q_rank', 'q_text', 'q_option1', 'q_option2', 'q_option3', 'q_option4', 'q_answer',
         'q_ask_time', 'no_times_ques_served', 'no_times_anwered_correctly', 'no_times_anwered_incorrectly',
         'difficulty_score'])

AIP/templates/AIP/add.html
<h2>New Question</h2>
      <form method="POST">{%  csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="save btn btn-default">Add Question</button>
      </form>

AIP/templates/AIP/begin.html
{% load static %}
{% load socialaccount %}
{% providers_media_js %}
<!DOCTYPE HTML>
<!--
   QuizHop
   -->
<html>
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <title> Quiz Hop </title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="Adaptive Interview Poral" />
      <!-- Animate.css -->
      <link rel="stylesheet" href="{% static 'css/animate.css'%}">
      <!-- Icomoon Icon Fonts-->
      <link rel="stylesheet" href="{% static 'css/icomoon.css'%}">
      <!-- Themify Icons-->
      <link rel="stylesheet" href="{% static 'css/themify-icons.css'%}">
      <!-- Bootstrap  -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
      <!-- Theme style  -->
      <link rel="stylesheet" href="{% static 'css/style.css'%}">
   </head>
   <body>
      <div class="gtco-loader"></div>
      <div id="page">
         <header id="gtco-header" class="gtco-cover" role="banner">
            <div class="gtco-container">
               <div class="display-tc">
                  <div class="row">
                     <p><h2><strong> Welcome !! You have selected {{subject}} in <i>{{rank}} </i> mode<strong></h2></p>
                     <p><strong> <i>This will be a multiple choice quiz and the questions will be dynamically enhanced based on your progress</i><strong></p>
                     <p><strong> <i>This is not a timed test , you can stop the test at any point you wish to <p><strong> <i>
                     <div class="col-md-7 copy animate-box">
                        <a href="{% url 'AIP:quiz' %}"class="btn btn-white">Start quiz</a>
                        <p></p>
                          <a style="color: #8C001A" href="/logout" >Logout</a>
                  </div>
               </div>
            </div>
         </header>
      </div>
      </div>
      <!-- jQuery -->
      <script src="{% static 'js/jquery.min.js'%}"></script>
      <!-- jQuery Easing -->
      <script src="{% static 'js/jquery.easing.1.3.js'%}"></script>
      <!-- Bootstrap -->
      <script src="{% static 'js/bootstrap.min.js'%}"></script>
      <!-- Waypoints -->
      <script src="{% static 'js/jquery.waypoints.min.js'%}"></script>
      <!-- Carousel -->
      <script src="{% static 'js/owl.carousel.min.js'%}"></script>
      <!-- Magnific Popup -->
      <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
      <script src="{% static 'js/magnific-popup-options.js'%}"></script>
      <!-- Main -->
      <script src="{% static 'js/main.js' %}"></script>
      </div>
   </body>
</html>

AIP/templates/AIP/beginsimple.html
{% load static %}
{% load socialaccount %}
{% providers_media_js %}
<!DOCTYPE HTML>
<!--
   QuizHop
   -->
<html>
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <title> Quiz Hop </title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="Adaptive Interview Poral" />
      <!-- Animate.css -->
      <link rel="stylesheet" href="{% static 'css/animate.css'%}">
      <!-- Icomoon Icon Fonts-->
      <link rel="stylesheet" href="{% static 'css/icomoon.css'%}">
      <!-- Themify Icons-->
      <link rel="stylesheet" href="{% static 'css/themify-icons.css'%}">
      <!-- Bootstrap  -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
      <!-- Theme style  -->
      <link rel="stylesheet" href="{% static 'css/style.css'%}">
   </head>
   <body>
      <div class="gtco-loader"></div>
      <div id="page">
         <header id="gtco-header" class="gtco-cover" role="banner">
            <div class="gtco-container">
               <div class="display-tc">
                  <div class="row">
                     <p><h2><strong> Welcome !! You have selected {{subject}} in <i>{{rank}} </i> mode<strong></h2></p>
                     <p><strong> <i>This will be a multiple choice quiz with total 30 questions </i><strong></p>
                     <p><strong> <i>This is not a timed test , you can stop the test at any point you wish to <p><strong> <i>
                     <div class="col-md-7 copy animate-box">
                        <a href="{% url 'AIP:quizsimple' %}"class="btn btn-white">Start quiz</a>
                        <p></p>
                          <strong> <a style="color: #8C001A" href="/logout" ">Logout</a></strong>
                    </div>
                  </div>
               </div>
            </div>
         </header>
      </div>
      </div>
      <!-- jQuery -->
      <script src="{% static 'js/jquery.min.js'%}"></script>
      <!-- jQuery Easing -->
      <script src="{% static 'js/jquery.easing.1.3.js'%}"></script>
      <!-- Bootstrap -->
      <script src="{% static 'js/bootstrap.min.js'%}"></script>
      <!-- Waypoints -->
      <script src="{% static 'js/jquery.waypoints.min.js'%}"></script>
      <!-- Carousel -->
      <script src="{% static 'js/owl.carousel.min.js'%}"></script>
      <!-- Magnific Popup -->
      <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
      <script src="{% static 'js/magnific-popup-options.js'%}"></script>
      <!-- Main -->
      <script src="{% static 'js/main.js' %}"></script>
      </div>
   </body>
</html>

AIP/templates/AIP/question_upload.html
{% if messages %}
    {% for message in messages %}
        <div>
            <strong>{{message|safe}}</strong>
        </div>
    {% endfor %}
{% else %}
{{order}}
<form method = "post" enctype="multipart/form-data">
    {% csrf_token %}
    <label > Upload a file </label>
    <input type ="file" name="file">
    <p>Only accepts CSV files</p>
    <button type="submit">Upload</button>
</form>
{% endif %}

AIP/templates/AIP/quizbucket.html
{% load static %}
{% load socialaccount %}
{% providers_media_js %}
<!DOCTYPE HTML>
<!--
   QuizHop
   -->
<html>
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <title> Quiz Hop </title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="Adaptive Interview Poral" />
      <link href="https://fonts.googleapis.com/css?family=Raleway:100,300,400,700" rel="stylesheet">
      <!-- Animate.css -->
      <link rel="stylesheet" href="{% static 'css/animate.css'%}">
      <!-- Icomoon Icon Fonts-->
      <link rel="stylesheet" href="{% static 'css/icomoon.css'%}">
      <!-- Themify Icons-->
      <link rel="stylesheet" href="{% static 'css/themify-icons.css'%}">
      <!-- Bootstrap  -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
      <!-- Theme style  -->
      <link rel="stylesheet" href="{% static 'css/style.css'%}">
   </head>
   <body>

      <div class="gtco-loader"></div>
      <div id="page">
         <header id="gtco-header" class="gtco-cover" role="banner">
            <div class="gtco-container">
               <div class="display-tc">
                   <form id="form" name="form" method="post" action="/addquiz/">{%  csrf_token %}
                      {{ form.as_p }}
                      <p><strong><i style="color:#000000">Welcome {{user}} !!<i></strong></p>
                      <p><strong><i style="color:#000000">Quizzes in your bucket</i></strong></p>
                       <div class="col-md-7 copy animate-box">
                          <strong> <a style="color: #8C001A" href="/logout" >Logout</a></strong>
                           <p></p>
                        </div>
                        </form>

                        <table class="table mb-0" >
                           <thead>
                             <tr>
                               <th colspan="3">Quiz</th>
                               <th colspan="3">Name</th>
                               <th colspan="3">Questions</th>
                               <th colspan="3">Quiz Link</th>
                               <th></th>
                             </tr>
                           </thead>
                           <tbody>
                             {% for quiz in quizzes %}
                               <tr>
                                 <td class="align-middle">{{ quiz.quiz_name }}</a></td>
                                  <td></td>
                                  <td></td>
                                 <td class="align-middle">{{ quiz.quiz_OrgIdentifier }}</td>
                                  <td></td>
                                    <td></td>
                                 <td class="align-middle">{{ quiz.quiz_noofquest }}</td>
                                  <td></td>
                                    <td></td>
                                   <td>
                                   <strong> <a style="color: #8C001A" href="/quiz/{{ quiz.pk }}" >/quiz/{{ quiz.pk }}</a></strong>
                                 </td>
                                  <td></td>
                                  <td class="text-right">
                                      <a href="{% url 'AIP:takequiz' quiz.pk %}" class="btn btn-primary">Start quiz</a>
                                 </td>
                               </tr>
                             {% endfor %}

                           </tbody>
                         </table>
               </div>
            </div>
         </header>
      </div>
      </div>
      <!-- jQuery -->
      <script src="{% static 'js/jquery.min.js'%}"></script>
      <!-- jQuery Easing -->
      <script src="{% static 'js/jquery.easing.1.3.js'%}"></script>
      <!-- Bootstrap -->
      <script src="{% static 'js/bootstrap.min.js'%}"></script>
      <!-- Waypoints -->
      <script src="{% static 'js/jquery.waypoints.min.js'%}"></script>
      <!-- Carousel -->
      <script src="{% static 'js/owl.carousel.min.js'%}"></script>
      <!-- Magnific Popup -->
      <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
      <script src="{% static 'js/magnific-popup-options.js'%}"></script>
      <!-- Main -->
      <script src="{% static 'js/main.js' %}"></script>
      </div>
   </body>
</html>

AIP/templates/AIP/report.html
{% load static %}
{% load socialaccount %}
{% providers_media_js %}
<!DOCTYPE HTML>
<!--
  QuizHop
   -->
<html>
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <title> Quiz Hop </title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="Adaptive Interview Poral" />
      <!-- Animate.css -->
      <link rel="stylesheet" href="{% static 'css/animate.css'%}">
      <!-- Icomoon Icon Fonts-->
      <link rel="stylesheet" href="{% static 'css/icomoon.css'%}">
      <!-- Themify Icons-->
      <link rel="stylesheet" href="{% static 'css/themify-icons.css'%}">
      <!-- Bootstrap  -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
      <!-- Theme style  -->
      <link rel="stylesheet" href="{% static 'css/style.css'%}">
   </head>
   <body>
      <div class="gtco-loader"></div>
      <div id="page">
         <header id="gtco-header" class="gtco-cover" role="banner">
            <div class="gtco-container">
               <div class="display-tc">
                     <h3><strong>Total score  : {{score}} %</strong></h3>
                  Total questions asked  : {{total_q_asked}}       Answered correctly     : {{total_q_ans_correct}}
                     <style>
                        table, th, td {
                        border: 1px solid black;
                        border-collapse: collapse;
                        }
                        th, td {
                        padding: 3px;
                        }
                        th {
                        text-align: left;
                        }
                     </style>
                     </head>
                     <body>
                        <table style="width:100% color = ">
                           <tr>
                              <th style="color:#000000"> <i>Concept  </i> </th>
                              <th style="color:#000000"> <i> Score  </i></th>
                           </tr>
                          {% for key, value in cat_dict.items %}
                           <tr>
                              <td style="color:#0000ff" > {{ key }}    </td>
                              <td style="color:#0000ff" > {{ value }}  </td>
                           </tr>
                           {% endfor %}
                        </table>
                        <p></p>
                        <!--<a href="{% url 'AIP:pickskill' %}" class="btn btn-white">Start Over</a>-->

                        <form method ="post" action="/comment/">{%csrf_token%}
                           <b style="color:#000000">Would you like to add a Comment or any suggestions:</b><br>
                           <textarea rows=3 cols=80  name="comment" required></textarea><br>
                           <input type="submit" value="Add Comment"  style="color:#000000">
                           <i>{{commsuccess}} </i>
                        </form>

                        <form method ="post" action="/question/" >{%csrf_token%}
                           <b style="color:#000000">Add a New Question:</b><br>
                           <textarea rows=3 co  ls =80  name="question" required></textarea><br>
                           <input type="submit" value="Add Question" style="color:#000000" >
                           <i> {{quessuccess}} </i>
                           <br>
                        </form>

                        <form method ="post" enctype="multipart/form-data" action="/upload/">{%csrf_token%}
                           <strong style="color:#000000">Upload a Question:</strong>
                           <input type="file" name="document" >
                           <br>
                           <input type="submit" value="Upload File" style="color:#696969" >
                           {% if url %}
                           <span style="margin-left: 40px;"> Uploaded File : <a href = "{{ url }}" style="color:maroon;" span style>{{url}}</a></span>
                           {% endif %}

                           <p></p>
                           <strong> <a style="color: #8C001A" href="/logout" >Logout</a></strong>
                        </form>
                  </div>

               </div>
            </div>
         </header>
      </div>
      </div>
      <!-- jQuery -->
      <script src="{% static 'js/jquery.min.js'%}"></script>
      <!-- jQuery Easing -->
      <script src="{% static 'js/jquery.easing.1.3.js'%}"></script>
      <!-- Bootstrap -->
      <script src="{% static 'js/bootstrap.min.js'%}"></script>
      <!-- Waypoints -->
      <script src="{% static 'js/jquery.waypoints.min.js'%}"></script>
      <!-- Carousel -->
      <script src="{% static 'js/owl.carousel.min.js'%}"></script>
      <!-- Magnific Popup -->
      <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
      <script src="{% static 'js/magnific-popup-options.js'%}"></script>
      <!-- Main -->
      <script src="{% static 'js/main.js' %}"></script>
      </div>
   </body>
</html>